export const employees = [
    {id: 1, first: "Nhim", last: "Nguyen"},
    {id: 1, first: "Long", last: "Huynh"},
    {id: 1, first: "Kai", last: "Ton"},
    {id: 1, first: "Jen", last: "Pham"},
    {id: 1, first: "Ichita", last: "Kaido"},
    {id: 1, first: "Ola", last: "Halo"},
    {id: 1, first: "Minas", last: "Huynh"},
    {id: 1, first: "Tu", last: "Huynh"},
    {id: 1, first: "Kiki", last: "Sigrit"},
    {id: 1, first: "Gau", last: "Huynh"},
    {id: 1, first: "Bento", last: "To"},
    {id: 1, first: "Fujito", last: "Fukio"},
    {id: 1, first: "Kenne", last: "Lovegood"},
    {id: 1, first: "Okta", last: "Yasuo"},
    {id: 1, first: "Hanh", last: "Nhat"},
    {id: 1, first: "Lulu", last: "Huynh"},
    {id: 1, first: "Alaska", last: "Baka"},
    {id: 1, first: "Lulu", last: "To"},
    {id: 1, first: "Nhim", last: "Okta"},
    {id: 1, first: "To", last: "Kien"},
    {id: 1, first: "Patrick", last: "Halo"},
]